// Enhanced Planet configuration with realistic data and improved visuals
const PLANET_DATA = [
  {
    name: "Mercury",
    color: "#8C7853",
    glowColor: "#B8A082",
    size: 0.12,
    distance: 2.5,
    speed: 4.15, // Fastest orbital speed
    rotationSpeed: 0.004,
    description: "The smallest planet and closest to the Sun with extreme temperatures",
    realDistance: "57.9 million km",
    realSpeed: "47.4 km/s",
    moons: 0,
    dayLength: "59 Earth days",
    yearLength: "88 Earth days",
    atmosphere: "None",
    temperature: "-173°C to 427°C",
  },
  {
    name: "Venus",
    color: "#FFC649",
    glowColor: "#FFD700",
    size: 0.16,
    distance: 3.2,
    speed: 3.5,
    rotationSpeed: -0.002, // Retrograde rotation
    description: "The hottest planet with a thick, toxic atmosphere of carbon dioxide",
    realDistance: "108.2 million km",
    realSpeed: "35.0 km/s",
    moons: 0,
    dayLength: "243 Earth days",
    yearLength: "225 Earth days",
    atmosphere: "96% CO₂, 3.5% N₂",
    temperature: "462°C",
  },
  {
    name: "Earth",
    color: "#6B93D6",
    glowColor: "#87CEEB",
    size: 0.18,
    distance: 4.0,
    speed: 2.98,
    rotationSpeed: 0.016,
    description: "Our home planet, the only known planet with life and liquid water",
    realDistance: "149.6 million km",
    realSpeed: "29.8 km/s",
    moons: 1,
    dayLength: "24 hours",
    yearLength: "365.25 days",
    atmosphere: "78% N₂, 21% O₂",
    temperature: "-89°C to 58°C",
  },
  {
    name: "Mars",
    color: "#CD5C5C",
    glowColor: "#FF6347",
    size: 0.14,
    distance: 5.2,
    speed: 2.41,
    rotationSpeed: 0.017,
    description: "The red planet with the largest volcano and canyon in the solar system",
    realDistance: "227.9 million km",
    realSpeed: "24.1 km/s",
    moons: 2,
    dayLength: "24.6 hours",
    yearLength: "687 Earth days",
    atmosphere: "95% CO₂, 3% N₂",
    temperature: "-87°C to -5°C",
  },
  {
    name: "Jupiter",
    color: "#D2691E",
    glowColor: "#DAA520",
    size: 0.6,
    distance: 7.8,
    speed: 1.31,
    rotationSpeed: 0.045,
    description: "The largest planet, a gas giant with a Great Red Spot storm",
    realDistance: "778.5 million km",
    realSpeed: "13.1 km/s",
    moons: 95,
    dayLength: "9.9 hours",
    yearLength: "12 Earth years",
    atmosphere: "89% H₂, 10% He",
    temperature: "-108°C",
  },
  {
    name: "Saturn",
    color: "#FAD5A5",
    glowColor: "#F0E68C",
    size: 0.5,
    distance: 10.5,
    speed: 0.97,
    rotationSpeed: 0.038,
    description: "Famous for its spectacular ring system made of ice and rock",
    realDistance: "1.43 billion km",
    realSpeed: "9.7 km/s",
    moons: 146,
    dayLength: "10.7 hours",
    yearLength: "29 Earth years",
    atmosphere: "96% H₂, 3% He",
    temperature: "-139°C",
  },
  {
    name: "Uranus",
    color: "#4FD0E7",
    glowColor: "#00CED1",
    size: 0.35,
    distance: 13.8,
    speed: 0.68,
    rotationSpeed: 0.03,
    description: "An ice giant tilted on its side with faint rings",
    realDistance: "2.87 billion km",
    realSpeed: "6.8 km/s",
    moons: 28,
    dayLength: "17.2 hours",
    yearLength: "84 Earth years",
    atmosphere: "83% H₂, 15% He, 2% CH₄",
    temperature: "-197°C",
  },
  {
    name: "Neptune",
    color: "#4169E1",
    glowColor: "#1E90FF",
    size: 0.34,
    distance: 17.2,
    speed: 0.54, // Slowest orbital speed
    rotationSpeed: 0.032,
    description: "The windiest planet with supersonic winds up to 2,100 km/h",
    realDistance: "4.50 billion km",
    realSpeed: "5.4 km/s",
    moons: 16,
    dayLength: "16.1 hours",
    yearLength: "165 Earth years",
    atmosphere: "80% H₂, 19% He, 1% CH₄",
    temperature: "-201°C",
  },
]

// Enhanced Animation and performance settings
const ANIMATION_CONFIG = {
  baseSpeed: 0.008, // Reduced for more realistic motion
  maxSpeed: 8.0,
  minSpeed: 0.0,
  speedStep: 0.1,
  targetFPS: 60,
  adaptiveQuality: true,
  starMovementSpeed: 0.0005,
  sunPulseIntensity: 0.3,
  planetGlowIntensity: 0.4,
}

// Enhanced UI Configuration
const UI_CONFIG = {
  tooltipDelay: 200,
  panelAnimationDuration: 400,
  themeTransitionDuration: 400,
  autoHideDelay: 4000,
  starCount: 15000,
  starFieldRadius: 300,
}

// Star field configuration
const STAR_CONFIG = {
  count: 15000,
  radius: 300,
  colors: ["#ffffff", "#ffffcc", "#ccccff", "#ffcccc", "#ccffcc"],
  sizes: [0.5, 0.8, 1.0, 1.2, 1.5],
  twinkleSpeed: 0.02,
  movementSpeed: 0.0003,
}
